apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector: # can remove selector, and let kubernetes decides for you
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready

# this should be stuck in unready state

# try to turn one of the pods into ready state by returning success by creating /var/ready file
# kubectl exec kubia-2r1qb -- touch /var/ready
