apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:          
      claimName: mongodb-pvc        


# init
# kubectl exec -it mongodb mongo

# write
# > use mystore
# switched to db mystore
# > db.foo.insert({name:'foo'})
# WriteResult({ "nInserted" : 1 })

# read
# > use mystore
# switched to db mystore
# > db.foo.find()
# { "_id" : ObjectId("57a61eb9de0cfd512374cc75"), "name" : "foo" }