apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc              
spec:
  resources:
    requests:                    
      storage: 1Gi               
  accessModes:                   
  - ReadWriteOnce                
  storageClassName: ""           # important


# setting storageClassName to be empty string binds it to a pre-defined PV instead of creating a new PV from default storage class
