apiVersion: batch/v1                  
kind: Job                             
metadata:
  name: batch-job
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:                         
        app: batch-job                
    spec:
      restartPolicy: OnFailure        # cannot use the default restart policy, which is 'Always'
      containers:
      - name: main
        image: luksa/batch-job