apiVersion: v1
kind: ResourceQuota
metadata:
  name: besteffort-notterminating-pods
spec:
  scopes:                 
  - BestEffort            
  - NotTerminating        
  hard:
    pods: 4               

# pods that are in the lowest QOS & not terminating
