apiVersion: v1
kind: Pod
metadata:
  name: pod-with-termination-message
spec:
  containers:
  - image: busybox
    name: main
    terminationMessagePath: /var/termination-reason                  
    command:
    - sh
    - -c
    - 'echo "I''ve had enough" > /var/termination-reason ; exit 1'

# The default file the process needs to write the message to is /dev/termination-log, but it can be changed by setting the terminationMessagePath

# If the container doesn’t write the message to any file, you can set the terminationMessagePolicy field to FallbackToLogsOnError. In that case, the last few lines of the container’s log are used as its termination message (but only when the container terminates unsuccessfully).
